# Generated by Django 5.1.2 on 2024-12-10 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cheating_images/')),
                ('cheating_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionfolder')),
            ],
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
