# Generated by Django 5.1.2 on 2024-12-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cheatingevent_delete_camera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheatingEvent',
        ),
    ]
