# Generated by Django 5.1.2 on 2024-12-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_detection_delete_capturedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detection',
        ),
    ]
