# Generated by Django 5.1.2 on 2024-12-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_detectionresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectionResult',
        ),
    ]
