# Generated by Django 5.1.2 on 2024-12-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_detection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detection',
        ),
    ]
