# Generated by Django 5.1.2 on 2024-12-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/')),
                ('result', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionfolder')),
            ],
        ),
    ]
