# Generated by Django 5.1.2 on 2024-12-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_capturedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapturedImage',
        ),
    ]
