# Generated by Django 5.1.2 on 2024-12-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_capturedimage_delete_capture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapturedImage',
        ),
    ]
